export const FETCH_HEROES = 'FETCH_HEROES';
export const DETAIL_HERO = 'DETAIL_HERO';

export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FAVORITE_HERO = 'FAVORITE_HERO';
export const UNFAVORITE_HERO = 'UNFAVORITE_HERO';